export enum GetterTypes {
  COUNTER__GET_DOUBLE_COUNT = "COUNTER__GET_DOUBLE_COUNT",
}

export enum MutationTypes {
  COUNTER__HANDLE_INCREMENT = "COUNTER__HANDLE_INCREMENT",
}

export enum ActionTypes {
  COUNTER__HANDLE_TIMEOUT_INCREMENT = "COUNTER__HANDLE_TIMEOUT_INCREMENT",
}
